version: "3.9"

services:
  db:
    image: postgres:15.4-alpine3.21
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - my_network

  app:
    build: .
    container_name: go_server
    env_file:
      - .env
    ports:
      - "${PORT}:8080"
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:


volumes:
  db-data:
